FORMAT: 1A
HOST: https://api.example.com

# Trybe API Documentation

# Group Hello Service

## GET /hello
+ Response 200 (text/plain)

        Hello!


# Group World Service

## GET /world
+ Response 200 (text/plain)

        World!
